# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKuUL376TvvVtW6vNu_HougEEUr3nDMw
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Load the dataset
hosp = pd.read_csv("HospitalCosts.csv")

# Analysis 1: Frequency of Visits by Patients
plt.hist(hosp['AGE'], bins=10, color='blue')
plt.title("Frequency of Visits by Patients")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

# Count of visits by age
age_counts = hosp['AGE'].value_counts().sort_index()
print("Count of visits by age:")
print(age_counts)

# Aggregate total charges by age
temp = hosp.groupby('AGE')['TOTCHG'].sum().reset_index()
temp.columns = ['Age', 'Expenditure']
print("\nTotal charges by age:")
print(temp)
max_expenditure_age = temp.loc[temp['Expenditure'].idxmax()]
print("\nAge group with maximum expenditure:")
print(max_expenditure_age)

# Analysis 2: Frequency of Diagnosis Related Groups
plt.hist(hosp['APRDRG'], color='blue')
plt.title("Frequency of Diagnosis Related Groups")
plt.xlabel("Categories")
plt.ylabel("Frequency")
plt.show()

# Aggregate total charges by APRDRG
temp2 = hosp.groupby('APRDRG')['TOTCHG'].sum().reset_index()
temp2.columns = ['Category', 'Expenditure']
print("\nTotal charges by Diagnosis Related Groups:")
print(temp2)
max_expenditure_category = temp2.loc[temp2['Expenditure'].idxmax()]
print("\nCategory with maximum expenditure:")
print(max_expenditure_category)

# Analysis 3: ANOVA by RACE
anova = sm.formula.ols('TOTCHG ~ RACE', data=hosp).fit()
print("\nANOVA results:")
print(anova.summary())

# Analysis 4: Linear Regression with FEMALE and AGE
lr_model = sm.formula.ols('TOTCHG ~ FEMALE + AGE', data=hosp).fit()
print("\nLinear Regression Model Summary:")
print(lr_model.summary())

# Analysis 5: Linear Regression with LOS, AGE, FEMALE, and RACE
lr_model2 = sm.formula.ols('LOS ~ AGE + FEMALE + RACE', data=hosp).fit()
print("\nLinear Regression Model Summary with LOS, AGE, FEMALE, and RACE:")
print(lr_model2.summary())

# Analysis 6: Linear Regression with all variables
lr_model3 = sm.formula.ols('TOTCHG ~ C(FEMALE) + AGE + RACE + LOS + APRDRG', data=hosp).fit()
print("\nLinear Regression Model Summary with all variables:")
print(lr_model3.summary())

